<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{2c2cd341-53ff-4a1d-8582-8b3c7243878f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//vnt 1
	bTest_1: BOOL;
	//CNT 2
	bTest_2: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>